import test from 'node:test';import assert from 'node:assert/strict';import {LuaVM,Authority}from '../scripts/lua-vm.mjs';
function check(code){const vm=new LuaVM();try{vm.exec(code);}finally{vm.close();}}
test('牛头优先级，104 张牌共 171 分',()=>check(`assert(Core.points(55)==7);assert(Core.points(11)==5);assert(Core.points(10)==3);assert(Core.points(5)==2);assert(Core.points(1)==1);local n=0;for i=1,104 do n=n+Core.points(i) end;assert(n==171)`));
test('第六张拿走原五张并留下自己',()=>check(`local s=Core.new(2,1);s.rows={{1,2,3,4,5},{40},{60},{80}};s.hands={{6},{90}};assert(Core.submit(s,1,6,s.token));assert(Core.submit(s,2,90,s.token));Core.step(s);assert(s.scores[1]==6);assert(#s.rows[1]==1 and s.rows[1][1]==6)`));
test('小牌可选任意行，后续牌使用更新后的桌面',()=>check(`local s=Core.new(2,1);s.rows={{20},{40},{60},{80}};s.hands={{5},{10}};Core.submit(s,2,10,s.token);Core.submit(s,1,5,s.token);Core.step(s);assert(s.waiting==1);assert(not Core.choose(s,2,4,s.token));assert(not Core.choose(s,1,0,s.token));assert(Core.choose(s,1,4,s.token));Core.step(s);assert(s.rows[4][1]==5 and s.rows[4][2]==10);assert(s.scores[1]==3)`));
test('重复、伪造和过期提交不改变状态；未亮牌不泄漏',()=>check(`local s=Core.new(2,22);local c=s.hands[1][1];assert(not Core.submit(s,1,105,s.token));assert(not Core.submit(s,1,c,s.token-1));assert(Core.submit(s,1,c,s.token));local rev=s.revision;assert(not Core.submit(s,1,c,s.token));assert(s.revision==rev);local v=Core.view(s,2);assert(#v.queue==0 and not v.pending and not v.hands and not v.rng);assert(v.ready[1]);v.hand[1]=999;assert(s.hands[2][1]~=999)`));
test('标准局仅在十轮完结后检查 66 分；下一手保留分数',()=>check(`local s=Core.new(2,3,'standard');s.scores={65,12};s.round=10;s.phase='resolve';s.queue={};Core.step(s);assert(s.phase=='handEnd');local token=s.token;Core.nextHand(s);assert(s.scores[1]==65 and s.handNo==2 and s.token>token);s.round=10;s.phase='resolve';s.queue={};s.scores[1]=66;Core.step(s);assert(s.phase=='gameOver');assert(Core.view(s,2).winners[1]==2)`));
test('超时自动选择规则可重复，旧超时不生效',()=>check(`local s=Core.new(8,4);local token=s.token;assert(not Core.timeout(s,token-1));Core.timeout(s,token);assert(s.phase=='reveal');for p=1,8 do assert(s.pending[p]) end;assert(not Core.timeout(s,token))`));
test('快照编解码与只向所属玩家发手牌',()=>check(`local s=Core.new(8,23);for p=1,8 do local v=Core.view(s,p);local decoded=Wire.decode(Wire.encode(v));assert(decoded.seat==p and #decoded.hand==10 and #decoded.rows==4 and #decoded.queue==0) end`));
test('2–8 人各 30 局：每一步卡牌守恒、最终正确结束',()=>{for(let n=2;n<=8;n++)for(let seed=1;seed<=30;seed++){const a=new Authority(n,seed);try{let steps=0;while(a.view(1).phase!=='gameOver'){assert.ok(steps++<200);const v=a.view(1);if(v.phase==='select'){for(let p=n;p>=1;p--)assert.equal(a.action(p,'submit',a.bot(p),v.token)[0],true);}else if(v.phase==='chooseRow')a.action(v.waiting,'choose',1+seed%4,v.token);else a.step();assert.equal(a.check(),true);}assert.equal(a.view(1).round,10);assert.equal(a.view(1).hand.length,0);}finally{a.close();}}});
